### ISSUE TITLE
crashes out after submit

### ISSUE THREAD

**Issue by scottjl** [SKEPDIMI/plwbbot#1]
```
/tmp/plwbbot/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:330
            throw new Error('Node is either not visible or not an HTMLElement');
                  ^

Error: Node is either not visible or not an HTMLElement
    at ElementHandle.clickablePoint (/tmp/plwbbot/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:330:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async ElementHandle.click (/tmp/plwbbot/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:392:26)
    at async DOMWorld.click (/tmp/plwbbot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:278:9)
    at async /tmp/plwbbot/execution_methods/browser.js:101:4
```

ubuntu 20.04

**Comment by SKEPDIMI** [comment]
This error is causes because the script attempted to use an element that wasn't present, which was the submit button in this case I believe. If you try and run this with `headless` mode turned off, can you see the submit button?

**Comment by scottjl** [comment]
how do i run it with headless mode turned off? sorry, but there isn't a lot in the way of usage documentation. :(

**Comment by SKEPDIMI** [comment]
Yeah sorry about that. Simply go to the file `./execution_methods/browser.js` and around line 17 you will see ...
```node
	const browser = await puppeteer.launch({
		headless: false
	});
```

Simply ensure that is set to false! If it is, next time you run the script, the browser will be visible and you will be able to check if the form is appearing or not. I also pushed a commit that will wait for the form to appear before doing anything, so you might also want to pull that change.
