### ISSUE TITLE
Never finishes execution

### ISSUE THREAD

**Issue by Mous3kteer** [SKEPDIMI/plwbbot#2]
On my installation, running "node . " will open the page, properly fill out the fields, and prompt to complete the Captcha, but after doing so and pressing enter, the script will submit the form and then just hang. It will display "Done!", but never actually finish execution. This means having to hit Ctrl-C to stop it and run it again. Is it supposed to loop, or stop, or is this known behavior?

**Comment by SKEPDIMI** [comment]
Yeah this is known behavior. I believe adding `process.exit(1)` would work to solve this

**Comment by SKEPDIMI** [comment]
Pushed a commit that does this. Thanks for pointing this out!
