### ISSUE TITLE
It worked too good

### ISSUE THREAD

**Issue by pm0u** [SKEPDIMI/plwbbot#4]
The request for the form is regularly failing with a `502` response. 

I tested this with and without a VPN, and multiple browsers. Multiple VPN locations, as well as double layer VPN connections.

It may be preferable in the future to wait for network idle:

```
	await page.waitForNavigation({ waitUntil: 'networkidle0', timeout:  40000 })
```
as it may take a while in the future with the heavy traffic  (the default of 30000 was not long enough in my case)

**Comment by SKEPDIMI** [comment]
Hey @pm0u I'm not sure what's going on here. But it may be possible this is due to their service possibly being taken down or in maintenance. I started a post about it here, since I too have been running into `502` responses https://www.reddit.com/r/esist/comments/pgq3bd/did_prolifewhistleblowercom_take_down_their/

**Comment by pm0u** [comment]
@SKEPDIMI yeah, it is very occasionally loading for me - can't seem to find a pattern. So, I think it may be getting overwhelmed. seems like its at least creating a major inconvenience for anyone hoping to use it!

**Comment by SKEPDIMI** [comment]
@pm0u likewise, I can't find a pattern of why it's doing this. It may be overwhelmed, they might be performing maintaince, or going offline permanently. Only time will tell. As to how it relates to this script, as long as there is no form, there is no way to submit the form, so I'm not sure this is a problem relating to the script itself I believe.

**Comment by pm0u** [comment]
@SKEPDIMI hah, no sorry this was more of a joke and just wanted to mention the ability to wait for network idle (since the form is loaded via AJAX) could be a decent solution if it continues to be very slow. I can close for the sake of housekeeping.
