### ISSUE TITLE
Fails to find selector element to insert into site

### ISSUE THREAD

**Issue by IsaacMilarky** [SKEPDIMI/plwbbot#5]
I keep getting this error when I try to run your script.

```/home/isaac/Repos/plwbbot/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:703
            throw new Error(`Error: failed to find element matching selector "${selector}"`);
                  ^

Error: Error: failed to find element matching selector "#forminator-field-textarea-1"
    at ElementHandle.$eval (/home/isaac/Repos/plwbbot/node_modules/puppeteer/lib/cjs/puppeteer/common/JSHandle.js:703:19)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async module.exports (/home/isaac/Repos/plwbbot/execution_methods/browser.js:34:2)
    at async /home/isaac/Repos/plwbbot/index.js:56:7
```
I would like to help. But I don't have much js experiance. Thank you!

**Comment by SKEPDIMI** [comment]
Hey @IsaacMilarky, we have had others mention this lately. This error is simply saying that we script tried to access an element (like an input) but it was not there. In the past hour or two, many people have reported that the form to the website is not showing up. We don't know why this is, but if the form is not displaying, the script will not be able to access the form and thus will crash.

See this post here: https://www.reddit.com/r/esist/comments/pgq3bd/did_prolifewhistleblowercom_take_down_their/

For debugging this, I would recommend you change the browser to run with `headless: false` and try seeing if the form is showing up or not.
